FROM node:16-alpine as build

ENV BACKEND_API_URL=http://localhost:9000

RUN mkdir /app

COPY . /app

RUN yarn --cwd /app install

RUN yarn --cwd /app build

FROM nginx:1.21-alpine

COPY --from=build /app/build /usr/share/nginx/html
